<?xml version="1.0" encoding="utf-8"?><Database Name="ufo_data" Class="ufoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=FEVREDREAM\SQLEXPRESS;Initial Catalog=ufo_data;Integrated Security=True" SettingsObjectName="UfoDataCenter.info.Properties.Settings" SettingsPropertyName="ufo_dataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ufo_collections" Member="ufo_collections">
    <Type Name="ufo_collection">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[database]" Member="database" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="collection" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>